#!/usr/bin/env python

# Copyright (c) 2011, Willow Garage, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of the Willow Garage, Inc. nor the names of its
#      contributors may be used to endorse or promote products derived from
#       this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import rospy

from geometry_msgs.msg import Twist

import sys, select, termios, tty

msg = """
Control Your Turtlebot!
---------------------------
Moving around:
   u    i    o
   j    k    l
   m    ,    .

q/z : increase/decrease max speeds by 10%
w/x : increase/decrease only linear speed by 10%
e/c : increase/decrease only angular speed by 10%
space key, k : force stop
anything else : stop smoothly

CTRL-C to quit
"""

moveBindings = {
        'w':(0, 1, 0),
        'a':(-1, 0, 0),
        'd':(1, 0, 0),
        's':(0, -1, 0),
        'q':(0, 0, 1),
        'e':(0, 0, -1),
        'b':(0, 0, 0),
           }

speedBindings={
        'y':(0.8, 0.8, 0.8),
        'u':(0.9, 0.9, 0.9),
        'i':(1.0, 1.0, 1.0),
        'o':(1.1, 1.1, 1.1),
        'p':(1.2, 1.2, 1.2),
          }

def getKey():
    tty.setraw(sys.stdin.fileno())
    rlist, _, _ = select.select([sys.stdin], [], [], 0.1)
    if rlist:
        key = sys.stdin.read(1)
    else:
        key = ''

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
    return key

if __name__=="__main__":
    settings = termios.tcgetattr(sys.stdin)
    
    rospy.init_node('HeilsCar_teleop')
    pub = rospy.Publisher('cmd_vel', Twist, queue_size=5)

    speed_x = 0
    speed_y = 0
    speed_rot = 0

    speedx_factor = 1
    speedy_factor = 1
    speedrot_factor = 1
    total_factor = 100


    status = 0
    count = 0

    target_speed_x = 0
    target_speed_y = 0
    target_speed_rot = 0
    try:
        print msg
        while(1):
            key = getKey()
            print key
            if key in moveBindings.keys():
                speed_x = moveBindings[key][0]
                speed_y = moveBindings[key][1]
                speed_rot = moveBindings[key][2]
                count = 0
            elif key in speedBindings.keys():
                speedx_factor = speedx_factor * speedBindings[key][0]
                speedy_factor = speedy_factor * speedBindings[key][1]
                speedrot_factor = speedrot_factor * speedBindings[key][2]
                count = 0

                if (status == 14):
                    print msg
                status = (status + 1) % 15
            elif key == ' ' or key == 'k' :
                speed_x = 0
                speed_y = 0
                speed_rot = 0
                target_speed_x = 0
                target_speed_y = 0
                target_speed_rot = 0
            else:
                count = count + 1
                if count > 4:
                    speed_x = 0
                    speed_y = 0
                    speed_rot = 0
                if (key == '\x03'):
                    break

            target_speed_x = speedx_factor * speed_x * total_factor
            target_speed_y = speedy_factor * speed_y * total_factor
            target_speed_rot = speedrot_factor * speed_rot * total_factor

            twist = Twist()
            twist.linear.x = target_speed_x; twist.linear.y = target_speed_y; twist.linear.z = 0
            twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = target_speed_rot
            pub.publish(twist)

            # print("loop: {0}".format(count))
            # print("publihsed: vx: {0}, wy: {1}, rot: {2}".format(twist.linear.x, twist.linear.y, twist.angular.z))

    except:
        print "error!"

    finally:
        twist = Twist()
        twist.linear.x = 0; twist.linear.y = 0; twist.linear.z = 0
        twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = 0
        pub.publish(twist)

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)

